#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
# eval "`pip completion --zsh`"
### PATH
if [ -d "$HOME/.bin" ] ;
  then PATH="$HOME/.bin:$PATH"
fi

if [ -d "$HOME/.local/bin" ] ;
  then PATH="$HOME/.local/bin:$PATH"
fi

if [ -d "$HOME/Apps" ] ;
  then PATH="$HOME/Apps:$PATH"
fi

if [ -d "$HOME/.local/share/applications" ] ;
  then PATH="$HOME/.local/share/applications:$PATH"
fi

if [ -d "$HOME/snap/flutter/common/flutter/bin" ] ;
  then PATH="$HOME/snap/flutter/common/flutter/bin:$PATH"
fi
